# Generated by Django 3.1.1 on 2020-09-18 12:29

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('singer', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('last_update_pageId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded_Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=music.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('last_update_pageId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('singer', models.CharField(max_length=200)),
                ('playTime', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('release_date', models.DateTimeField()),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('last_update_pageId', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
            ],
        ),
    ]
